### PR TITLE
Fix a crash when storage_read_orig returns an error

### PR DESCRIPTION
**Pull request by b00f**
When storage_read return an error sputnik will crash
Please avoid using `unwrap` method.

### CODE REVIEW

**Comment by mersinvald** [comment]
These unwraps should be ensured to not to panic by the checks in https://github.com/ETCDEVTeam/sputnikvm/blob/master/src/eval/check.rs.

If something panics at this stage it means that there's an internal bug and that shouldn't be silenced. 

Please provide a test case to reproduce the panic you've encountered, or modify the precheck methods to ensure the data causing panic is prechecked and requested (in case it's storage value) before opcode goes to execution.

**Review by mersinvald — CHANGES_REQUESTED** [review]
described as a comment

**Comment by b00f** [comment]
> If something panics at this stage it means that there's an internal bug and that shouldn't be silenced.

Better to not use `unwarp` even there is an internal bug. We can use `panic("Critical bug...")` whenever the internal error happen. I got the crash when we run a test scrip inside Gallactic blockchain. After digging deep into the crash I found out that `has_reduced_sstore_gas_metering` flags has set to `true`. 

I also read about `unwarp` command. I found this [article](https://klausi.github.io/rustnish/2017/08/16/replacing-unwrap-and-avoiding-panics-in-rust.html). It says:  
> All unwrap() calls in none test code should be removed and covered by proper error handling.

**Comment by b00f** [comment]
> Please provide a test case to reproduce the panic you've encountered, or modify the precheck methods to ensure the data causing panic is prechecked and requested (in case it's storage value) before opcode goes to execution.

I am not familiar with the SputnikVM code. If you can explain me more I can add test case for this issue...

**Comment by mersinvald** [comment]
@b00f yeah, I can agree to that: we should be using `expect` here with a proper error description. I don't have time for refactoring at the time, but error-handling refactoring is on my list.

**Comment by mersinvald** [comment]
@b00f 
> I am not familiar with the SputnikVM code. If you can explain me more I can add test case for this issue...

Precheck is happening here: https://github.com/ETCDEVTeam/sputnikvm/blob/5943a5d1a647ff1802336cc5e1eb61f909bd6962/src/eval/mod.rs#L363

Errors are handled by precheck routines descriped in the check.rs file I linked above.
After precheck, the unwraps we're discussing should be guaranteed to be resolved as `Ok` or `Some` depending on their type.

If it panics there -- bug is in the precheck. So, what did you do to cause SputnikVM to fail there? How can I reproduce this panic?
Can you share the bytecode causing the panic?

**Comment by b00f** [comment]
>  How can I reproduce this panic?

It's hard to reproduce it. Steps to reproduce:
1- set the `has_reduced_sstore_gas_metering` flag to `true`
2- Deploy this contract:
```
pragma solidity ^0.4.24;

contract SimpleStorage {
	uint private _balance;
	uint private _storedData;
	address private owner;

	event notifyStorage(uint x);

	constructor() public {
		owner = msg.sender;
	}

	function set(uint x) public payable {
		_storedData = x;
		emit notifyStorage(x);
	}

	function get() public view returns (uint) {
		return _storedData;
	}

	function getOwner() public view returns (address){
		return owner;
	}

	function kill() public{
		selfdestruct(owner);
	}
}
```
bytecode: `608060405234801561001057600080fd5b5033600260006101000a815481600160a060020a030219169083600160a060020a031602179055506101be806100476000396000f3006080604052600436106100615763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166341c0e1b5811461006657806360fe47b11461007d5780636d4ce63c14610088578063893d20e8146100b0575b600080fd5b34801561007257600080fd5b5061007b610107565b005b61007b60043561012d565b34801561009457600080fd5b5061009d610168565b6040805191825251602090910181900390f35b3480156100bc57600080fd5b506100c561016e565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b60025473ffffffffffffffffffffffffffffffffffffffff60006101000a909104811616ff5b60018190556040805182815290517f23f9887eb044d32dba99d7b0b753c61c3c3b72d70ff0addb9a843542fd7642129160200181900390a150565b60015490565b60025460006101000a900473ffffffffffffffffffffffffffffffffffffffff16905600a165627a7a7230582001a5bb7dbc53c4e0e7acc1b23010f4dd1415e0b440e8784ac8ce8d0696c841720029`
3- It should panic

**Comment by mersinvald** [comment]
@b00f thanks, I'll look into it and will get back to you with the results.

**Pull request closed without merging**
